
lang: en
title: Hydejack
copyright: © 2024. All rights reserved.

# Minimal theme config: black background, red accents, white text
accent_color: rgb(220,20,60)   # red accent (crimson)
theme_color: rgb(0,0,0)       # black background

google_fonts: false

hydejack:
  # minimal dark mode settings
  dark_mode:
    always: true
    dynamic: false
    icon: true
    color_scheme:
      dark:
        background: rgb(0,0,0)
        surface: rgb(10,10,10)
        text: rgb(255,255,255)
        accent: rgb(220,20,60)

sass:
  style: compressed
